#Import Libraries

Notr I did this part of the work on google colab so you might have to install the libraries which I have not added to the requirements.txt file by yourself, thank you

In [ ]:
import pickle
import os
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [ ]:
# Define the directory where all the pickle files are stored
pickle_dir = './pickle_data'  # Update with the path to your pickle files

# Initialize lists to hold data and labels
data = []
labels = []

# Loop through all the pickle files in the specified directory
for filename in os.listdir(pickle_dir):
    if filename.endswith('.pickle'):
        with open(os.path.join(pickle_dir, filename), 'rb') as f:
            data_dict = pickle.load(f)

            # Add data and labels from the current pickle file
            data.extend(data_dict['data'])
            labels.extend(data_dict['labels'])

#Data Preprocessing

In [ ]:
# Convert to numpy arrays
data = np.asarray(data)
labels = np.asarray(labels)

In [3]:
data,labels

(array([[0.05546527, 0.56381139, 0.15827014, ..., 0.07150623, 0.03433628,
         0.12176374],
        [0.05652921, 0.53700131, 0.15578946, ..., 0.06563127, 0.05089188,
         0.12211096],
        [0.0599577 , 0.52526981, 0.15734272, ..., 0.0648033 , 0.04862627,
         0.11821669],
        ...,
        [0.        , 0.33251974, 0.03970164, ..., 0.43121585, 0.15227744,
         0.40552565],
        [0.        , 0.33551592, 0.03773062, ..., 0.43510818, 0.14947781,
         0.41032994],
        [0.        , 0.33078617, 0.03748596, ..., 0.43224794, 0.15270759,
         0.40866202]]),
 array(['4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4',
        '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4',
        '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4',
        '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4',
        '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4',
        '4', '4', '4', '4', '4', '4', '4', '

#Feature Engineering data

In [ ]:
# Encode labels as integers (if not already in numeric format)
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(labels)

#Split Data For Training and testing

In [ ]:
# Split the data into training and testing sets using stratified sampling
x_train, x_test, y_train, y_test = train_test_split(data, y_encoded, test_size=0.2, shuffle=True, stratify=y_encoded)

#Train the model Using Random Forest

In [ ]:
# Initialize the RandomForestClassifier model
model = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model on the training data
model.fit(x_train, y_train)

# Predict on the test data
y_predict = model.predict(x_test)

#Evaluation of my model

In [ ]:
# Calculate accuracy
score = accuracy_score(y_predict, y_test)
print(f'{score * 100:.2f}% of samples were classified correctly!')


100.00% of samples were classified correctly!


#Saving the model

In [9]:
# Save the trained model to a pickle file
with open('model.p', 'wb') as f:
    pickle.dump({'model': model}, f)

print("Model saved successfully!")

Model saved successfully!


#Making analysis of the results

In [8]:
# Get the confusion matrix
conf_matrix = confusion_matrix(y_test, y_predict)
print("Confusion Matrix:\n", conf_matrix)

# Display classification report
class_report = classification_report(y_test, y_predict)
print("Classification Report:\n", class_report)


Confusion Matrix:
 [[20  0  0  0  0  0  0  0  0  0]
 [ 0 20  0  0  0  0  0  0  0  0]
 [ 0  0 20  0  0  0  0  0  0  0]
 [ 0  0  0 20  0  0  0  0  0  0]
 [ 0  0  0  0 20  0  0  0  0  0]
 [ 0  0  0  0  0 20  0  0  0  0]
 [ 0  0  0  0  0  0 20  0  0  0]
 [ 0  0  0  0  0  0  0 20  0  0]
 [ 0  0  0  0  0  0  0  0 20  0]
 [ 0  0  0  0  0  0  0  0  0 20]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        20
           1       1.00      1.00      1.00        20
           2       1.00      1.00      1.00        20
           3       1.00      1.00      1.00        20
           4       1.00      1.00      1.00        20
           5       1.00      1.00      1.00        20
           6       1.00      1.00      1.00        20
           7       1.00      1.00      1.00        20
           8       1.00      1.00      1.00        20
           9       1.00      1.00      1.00        20

    accuracy                  

#COMMENTS
The model is perfect, it was able to reach all the standards required to be able to trust the results from a prediction.

The confusion matrix also says the same story

#Backing up data on the Google Clound, since I used Google Colab

!Note please don't run this part if you are not using google colab

In [10]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [11]:
pickle_dir = '/content/drive/MyDrive/dataset/cloudcomputing/models/'  # Update with the path to your Google Drive folder
os.makedirs(pickle_dir, exist_ok=True)


In [12]:
model_file_path = os.path.join(pickle_dir, 'random_forest_model.pickle')


with open(model_file_path, 'wb') as f:
    pickle.dump({'model': model}, f)

print(f"Model saved successfully at {model_file_path}")

Model saved successfully at /content/drive/MyDrive/dataset/cloudcomputing/models/random_forest_model.pickle
